---
title: "Filter-from-controls"
author: "John Sterrett"
date: "2024-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Load data
```{r}
lipids <- data.table::fread("../metabolome/Lipid_compounds_found.csv",
                            data.table=F)
aqueous <- data.table::fread("../metabolome/Aqueous_compounds_found.csv",
                            data.table=F)
```

# Filter data
```{r}
matcher <- function(x, pattern="not found"){
    squished <- stringr::str_squish(x)
    lowered <- stringr::str_to_lower(squished)
    return (lowered == pattern)
}



lipids.to.use <- lipids[,!duplicated(colnames(lipids))] %>% #remove dups
    dplyr::filter(matcher(lipids$`Searched by ion`)) %>% # get only not found in controls
    dplyr::select(-c("Searched by ion", "Searced by name")) # remove excess columns for downstream

aqueous.to.use <- aqueous[,!duplicated(colnames(aqueous))] %>% 
    dplyr::filter(matcher(aqueous$`Searched by ion`)) %>% 
    dplyr::select(-any_of(c("Searched by ion", "Searched by name")))
```

# Filtering numbers
```{r}
info_printer <- function(title, original, filtered){
    orig.rows <- nrow(original)
    filtered.rows <- nrow(filtered)
    
    print(paste(title, "---", 
                "The original dataset had", orig.rows,
                "compounds, and the filtered dataset has",
                filtered.rows, "compounds.",
                orig.rows-filtered.rows, 
                "compounds were removed."))
}

info_printer(title="LIPIDS", original=lipids, filtered=lipids.to.use)
info_printer(title="AQUEOUS", original=aqueous, filtered=aqueous.to.use)
```

# Save data
```{r}
write.csv(lipids.to.use, "../metabolome/Lipid_compounds_NOT_found.csv", quote=F)
write.csv(aqueous.to.use, "../metabolome/Aqueous_compounds_NOT_found.csv", quote=F)
```

