---
title: "Microbe-metabolite regression analysis"
author: "John Sterrett"
date: '2022-07-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               lme4, lmerTest,
               qiime2R,
               data.table,
               foreach,
               parallel)

'%ni%' <- Negate('%in%')

setwd("/Users/johnsterrett/Research-Projects/Reisdorph/GT-micro-metabo/analysis")


```

# Load data

```{r}
# read in genus level table
genus <- read_qza("../microbiome/L6-collapsed-table.qza")$data %>% as.data.frame()
genus_names <- row.names(genus)

# convert to relative abundance
genus <- sapply(genus,
                prop.table) * 100
genus <- genus %>% as.data.frame(row.names = genus_names)

# check that all colsums are 100
unique(colSums(genus))

genus <- t(genus) %>% as.data.frame()

rownames(genus)


# read in metadata
metadata <- fread("../metadata/mapping.tsv", sep = "\t")
rownames(metadata) <- metadata$`MetaboSampleID`

# read in metabolites
aqueous <- fread("../metabolome/raw_aqueous.tsv",
                 sep="\t", header = T) %>% as.data.frame()
aqueous <- aqueous %>% remove_rownames() %>% column_to_rownames(var="V1")

aqueous <- aqueous[rownames(aqueous) %ni% c("Compound Name", "Retention Time",
                                          "Measured Retention Time", "Product Mass",
                                         "QualifierMass", "CASNumber",
                                         "CompoundType", "ISTDCompoundName", 
                                         "Mass Column"),]
aqueous <- mutate_all(aqueous, function(x) as.numeric(as.character(x)))


# read in lipids
lipids <- fread("../metabolome/raw_lipid.tsv",
                sep="\t",
                header = T)

rownames(lipids) <- lipids$V1
lipids <- lipids %>% remove_rownames() %>% column_to_rownames(var="V1")

lipids <- lipids[rownames(lipids) %ni% c("Compound Name", "Retention Time",
                                          "Measured Retention Time", "Product Mass",
                                         "QualifierMass", "CASNumber",
                                         "CompoundType", "ISTDCompoundName", 
                                         "Mass Column"),]
lipids <- mutate_all(lipids, function(x) as.numeric(as.character(x)))

# map genus sample ids to metabolomics sample ids
new_genus_sample_ids <- c()
for (x in row.names(genus)){
    sampleid <- metadata[metadata$`#SampleID`==x, "MetaboSampleID"][[1,1]]
    new_genus_sample_ids <- c(new_genus_sample_ids, sampleid)
}

for (i in 1:length(new_genus_sample_ids)){
    print(paste0("Mapping ", rownames(genus)[i], 
                 " to ", new_genus_sample_ids[i]))
}

rownames(genus) <- new_genus_sample_ids

# sort dataframes
 genus <- genus[order(as.numeric(rownames(genus))),,drop=FALSE]
 metadata <- metadata[order(as.numeric(rownames(metadata))),,drop=FALSE]
 aqueous <- aqueous[order(as.numeric(rownames(aqueous))),,drop=FALSE]
 lipids <- lipids[order(as.numeric(rownames(lipids))),,drop=FALSE]
```

# Transform data
```{r}
# hist before transformation
hist(genus[, 1:3])

# arcsinh transform microbiome data
genus <- genus %>% mutate_all(function(x) log(x + sqrt(x^2 + 1)))

# hist after transformation
hist(genus[, 1:3])

```



# Assess sparsity
```{r}
# microbiome
feature_sparsity <- genus %>% sapply(function(x) coop::sparsity(as.matrix(x)))
hist(feature_sparsity, breaks=10)

# aqueous
feature_sparsity <- aqueous %>% sapply(function(x) coop::sparsity(as.matrix(x)))
hist(feature_sparsity, breaks=50)
unique(feature_sparsity)


# aqueous
feature_sparsity <- lipids %>% sapply(function(x) coop::sparsity(as.matrix(x)))
hist(feature_sparsity, breaks=50)
unique(feature_sparsity)
```


# Regressions
```{r}
all_df <- cbind(genus, aqueous, lipids)
metabo_df <- cbind(aqueous, lipids)

lm_df <- all_df %>% janitor::clean_names()
feat_name_mapped <- data.frame(new=names(lm_df), old=names(all_df))

# Janet Seibert's suggested ddfits threshold
ddfits_thresh <- 4


results <- data.frame(matrix(nrow=0, ncol=5))
names(results) <- c("microbe", "metabolite", "p", "beta", "max_influence") 


# create function to parallelize
run_lm <- function(i, j){
    microbe <- feat_name_mapped[feat_name_mapped$old==genus_names[i], 
                                "new"]
    metabolite <- feat_name_mapped[feat_name_mapped$old==names(metabo_df)[j], 
                                   "new"]
    # create formula
    formula <- paste(metabolite, "~", microbe)
    # run model
    mod <- lm(formula, lm_df)
    
    # extract p and beta
    p <- coef(summary(mod))[microbe,"Pr(>|t|)"]
    my_beta <- coef(summary(mod))[microbe,"Estimate"]
    
    # calculate maximum influence of any point
    dffits <- as.data.frame(dffits(mod))
    max_influence <- max(abs(dffits))
    
    # add new results to df
    new_results <- list(microbe, metabolite, p, my_beta, max_influence)
    return(new_results)
}

#setup parallel backend to use many processors
cores <- detectCores()
cl <- makeCluster(cores[1]-1) #not to overload your computer
doParallel::registerDoParallel(cl)

#registerDoSNOW(cl) # not sure what this is
iterations_i <- ncol(genus)
iterations_j <- ncol(metabo_df)
pb <- txtProgressBar(max = iterations_i, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)


results_parallel <- data.frame(matrix(nrow=ncol(genus)*ncol(metabo_df), 
                                      ncol=5))
names(results_parallel) <- c("microbe", "metabolite", "p", "beta", "max_influence") 

ptm <- proc.time()
y <- foreach(i=1:iterations_i, 
             .combine=cbind, 
             .options.snow = opts) %:%
    foreach(j=1:iterations_j, 
            .combine=cbind, 
            .options.snow = opts) %dopar% {
    progress(i)
  # print(paste0("trial ",trial," out of ", nrow(allRow)))
                 #results_for_taxa <- data.frame(matrix(nrow=100, ncol=5))
                 #for(j in 1:ncol(metabo_df)){
                     run_lm(i,j)
                 #}
  #list(v = thisRun[["output1"]], w = thisRun[["output2"]], x = thisRun[["output3"]])
            }

print(paste0((proc.time() - ptm)[["elapsed"]]/60, " minutes"))

#stop cluster
stopCluster(cl)


results_parallel$microbe <- unlist(y[1,])
results_parallel$metabolite <- unlist(y[2,])
results_parallel$p <- unlist(y[3,])
results_parallel$beta <- unlist(y[4,])
results_parallel$max_influence <- unlist(y[5,])


results_parallel[results_parallel$p < 0.05, "beta"]

hist(results_parallel$beta, breaks=100)

hist(results_parallel$max_influence, breaks=20)



```

