---
title: "Whole Metabolome Ordination"
author: "John Sterrett"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r read_data}
aqueous <- read.csv("../metabolome/Whole_plasma_metabolome_aq_log2.csv", skip=4)
lipids <- read.csv("../metabolome/Whole_plasma_metabolome_lip_log2.csv", skip=4)

metadata <- read.csv("../metadata/mapping_nocomment.tsv", sep="\t")
```

```{r clean_data_helpers}
get_sample_columns <- function(column_names){
  return (column_names[grepl(column_names, pattern="Log2.normalized")])
}

get_sample_ids <- function(column_names, type="SBAQ"){
  gt_pattern <- paste0("GT_001_", type, "_")
  no_gt <- gsub(pattern=gt_pattern, replacement="", column_names)
  no_log2 <- gsub(pattern="_area2height..Log2.normalized.", replacement="", no_gt)
  return (no_log2)
}

get_sample_group <- function(sample_id, 
                             metadata, metadata_column="PID"){
  if(grepl(sample_id, pattern="QC")){
    return("Quality Control")
  }
  
  group <- metadata[metadata$MetaboSampleID==sample_id, metadata_column]
  if (group=="Control"){
    return ("Germ free")
  } else {
    return ("Humanized")
  }
}

```

```{r clean_data}
aqueous <- aqueous[get_sample_columns(colnames(aqueous))]
lipids <- lipids[get_sample_columns(colnames(lipids))]

colnames(aqueous) <- get_sample_ids(colnames(aqueous), type="SBAQ")
colnames(lipids) <- get_sample_ids(colnames(lipids), type="Lipid")

# Remove post-run cleanup from lipidsb
lipids <- lipids[,!grepl("Post_Run", colnames(lipids),)]

aqueous_mat <- as.matrix(t(aqueous))
lipids_mat <- as.matrix(t(lipids))
```

# Aqueous PCA
```{r ordinate_aqueous}
aqueous_prcomp <- prcomp(aqueous_mat)
aqueous_pca <- as.data.frame(aqueous_prcomp$x)
aqueous_pca_var_explained <- summary(aqueous_prcomp)$importance[2,]*100
aqueous_pca_var_explained <- format(round(x=aqueous_pca_var_explained, digits=1), 
                                    1)

sample_groups <- sapply(X=rownames(aqueous_pca), 
                      FUN=function(x){get_sample_group(x, metadata)})

aqueous_pca$sample_group <- sample_groups
aqueous_pca <- merge(aqueous_pca, metadata, by.x="row.names", by.y="MetaboSampleID", all.x=T)
aqueous_pca[is.null(aqueous_pca$Group), "Group"] <- "Quality Control"

a <- ggplot(aqueous_pca, 
       mapping=aes(x=PC1, y=PC2, color=sample_group)) +
  geom_point(size=4, alpha=0.8) +
  scale_color_manual(values=c("#dd8452","#4c72b0", "black"),
                     name=NULL) +
  theme_classic() +
  labs(x=paste0("PC1 (", aqueous_pca_var_explained[1], "%)"),
       y=paste0("PC2 (", aqueous_pca_var_explained[2], "%)"))
a

ggsave("../figures/whole_metabolome_pca.png", a)
ggsave("../figures/whole_metabolome_pca.pdf", a)
```


# Lipid PCA
```{r ordinate_lipids}
lipids_prcomp <- prcomp(lipids_mat)
lipids_pca <- as.data.frame(lipids_prcomp$x)
lipids_pca_var_explained <- summary(lipids_prcomp)$importance[2,]*100
lipids_pca_var_explained <- format(round(lipids_pca_var_explained, digits=1),
                                   1)

sample_group <- sapply(X=rownames(lipids_pca), 
                      FUN=function(x){get_sample_group(x, metadata)})
lipids_pca$group <- sample_group

b <- ggplot(lipids_pca, 
       mapping=aes(x=PC1, y=PC2, color=sample_group)) +
  geom_point(size=4, alpha=0.8) +
  scale_color_manual(values=c("#dd8452","#4c72b0", "black"),
                     name=NULL) +
  theme_classic() +
  labs(x=paste0("PC1 (", lipids_pca_var_explained[1], "%)"),
       y=paste0("PC2 (", lipids_pca_var_explained[2], "%)"))

b
ggsave("../figures/whole_lipidome_pca.png", b)
ggsave("../figures/whole_lipidome_pca.pdf", b)

```

```{r fig.height=6, fig.width=10}
a_nolegend <- a + guides(color="none")
full_plot <- cowplot::plot_grid(a_nolegend, b, labels=c("A", "B"), rel_widths=c(1,1.4))
full_plot

ggsave("../figures/whole_pca.pdf", full_plot, height=6, width=10)
ggsave("../figures/whole_pca.png", full_plot, height=6, width=10)
```